Lavoratr/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^', include('lavoratr.urls', namespace="lavoratr")),
    url(r'^admin/', include(admin.site.urls)),
)

lavoratr/urls.py
from django.conf.urls import patterns, url
from lavoratr import views
from djgeojson.views import GeoJSONLayerView
from lavoratr.models import Toilet

urlpatterns = patterns(
    '',
    url(r'^$', views.index, name='index'),
    url(
        r'^add_review/(?P<toilet_id>\d+)/$',
        views.add_review,
        name='add_review'
    ),
    url(r'^detail/(?P<toilet_id>\d+)/$', views.detail, name='detail'),
    url(
        r'^data.geojson$',
        GeoJSONLayerView.as_view(model=Toilet),
        name='data'
    ),
    url(
        r'^add_toilet/(?P<lat>-?\d+\.\d+)/(?P<lng>-?\d+\.\d+)/$',
        views.add_toilet,
        name='add_toilet'
    ),
    url(r'^submit_toilet/$', views.submit_toilet, name='submit_toilet'),
    url(
        r'^get_modal_data/(?P<toilet_id>\d+)/$',
        views.modal_data,
        name='modal_data'
    ),
    url(r'^submit_review/$', views.submit_review, name='submit_review'),
    url(r'^get.geojson.js$', views.get_geojson, name='get_geojson'),
    url(r'^registration$', views.registration, name='registration'),
    url(r'^login$', views.login, name='login'),
    url(r'^logil_submit$', views.login_submit, name='login_submit'),
    url(
        r'^registration_submit$',
        views.registration_submit,
        name='registration_submit'
    ),

)

lavoratr/models.py
from django.contrib.gis.db import models
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User


MALE = 'M'
FEMALE = 'F'
UNISEX = 'U'
SEX_CHOICES = (
    (MALE, 'Male'),
    (FEMALE, 'Female'),
    (UNISEX, 'Unisex'),
)


def validate_length(value):
    if len(value) < 5:
        raise ValidationError('%s is not longer than 5 characters' % value)


class Toilet(models.Model):
    location = models.CharField(
        max_length=50, verbose_name="Location in Building",
        validators=[validate_length]
    )
    building = models.CharField(
        max_length=50, blank=False, validators=[validate_length]
    )
    positive_ratings = models.IntegerField()
    negative_ratings = models.IntegerField()
    gender = models.CharField(max_length=1,
                              choices=SEX_CHOICES,
                              default=MALE)
    created = models.DateTimeField()
    single_occupancy = models.BooleanField(default=False)
    accesible = models.BooleanField(default=False)
    station = models.BooleanField(
        default=False, verbose_name='Changing Station'
    )
    times_authenticated = models.FloatField(default=0)
    point = models.PointField()
    objects = models.GeoManager()

    def __unicode__(self):
        return (str(self.location) + ', ' + str(self.building))


class Review(models.Model):
    user = models.ForeignKey(User)
    toilet = models.ForeignKey(Toilet)
    rating = models.IntegerField()
    comment_box = models.CharField(max_length=127, blank=True)
    created = models.DateTimeField()

    def __unicode__(self):
        return (str(self.toilet) + ': ' + str(self.rating))

lavoratr/forms.py
from django import forms
from django.core.exceptions import ValidationError

MALE = 'M'
FEMALE = 'F'
UNISEX = 'U'
SEX_CHOICES = (
    (MALE, 'Male'),
    (FEMALE, 'Female'),
    (UNISEX, 'Unisex'),
)


def validate_length(value):
    if len(value) < 5:
        raise ValidationError('%s is not longer than 5 characters' % value)


'''NOTE:  for rating: 1=like, 2 = dislike'''


class ToiletForm(forms.Form):
    location = forms.CharField(
        max_length=50, validators=[validate_length], required=True
    )
    building = forms.CharField(
        max_length=50, validators=[validate_length], required=True
    )
    gender = forms.ChoiceField(choices=SEX_CHOICES)
    rating = forms.IntegerField(min_value=1, max_value=2)
    single_occupancy = forms.BooleanField(required=False)
    accesible = forms.BooleanField(required=False)
    station = forms.BooleanField(required=False)
    comment_box = forms.CharField(max_length=127, required=False)
    lat = forms.FloatField()
    lng = forms.FloatField()


class ReviewForm(forms.Form):
    rating = forms.IntegerField(min_value=1, max_value=2)
    comment_box = forms.CharField(max_length=127, required=False)

lavoratr/views.py
from django.shortcuts import render, get_object_or_404
from django.utils import timezone, simplejson
from django.contrib.gis.geos import Point
from lavoratr.models import Toilet, Review
from lavoratr.serializers import ToiletSerializer
from lavoratr.forms import ToiletForm, ReviewForm
from rest_framework.renderers import JSONRenderer
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate, login as auth_login
from django.contrib.auth.models import User
from django.shortcuts import redirect


def index(request):
    latest_toilet_list = Toilet.objects.all()
    serializer = ToiletSerializer(latest_toilet_list)
    toilets_json = JSONRenderer().render(serializer.data)
    context = {
        'form': ToiletForm,
        'toilets_json': toilets_json,
        'latest_toilet_list': latest_toilet_list
    }
    return render(request, 'lavoratr/toilet.html', context)


def registration(request):
    return render(request, 'lavoratr/user_registration.html')


def login(request):
    return render(request, 'lavoratr/user_login.html')


def login_submit(request):
    username = request.POST['InputUsername']


def get_geojson(request):
    latest_toilet_list = Toilet.objects.all()
    serializer = ToiletSerializer(latest_toilet_list)
    toilets_json = JSONRenderer().render(serializer.data)
    return HttpResponse(toilets_json, content_type="application/json")


def detail(request, toilet_id):
    toilet = get_object_or_404(Toilet, id=toilet_id)
    reviews = Review.objects.filter(toilet=toilet)
    return render(
        request,
        'lavoratr/detail.html',
        {'toilet': toilet, 'reviews': reviews}
    )


def modal_data(request, toilet_id):
    toilet = get_object_or_404(Toilet, id=toilet_id)
    serializer = ToiletSerializer(toilet)
    toilet_json = JSONRenderer().render(serializer.data)
    return HttpResponse(toilet_json, content_type="application/json")


def get_user(username):
    try:
        return User.objects.get(username=username)
    except User.DoesNotExist:
        return None


def registration_submit(request):
    if request.method == "POST":
        email = request.POST['InputEmail']
        username = request.POST['InputUsername']
        password = request.POST['InputPassword']
        password_two = request.POST['InputPasswordConfirm']
        user = get_user(username)
        if password == password_two:
            if user is None:
                user = User.objects.create_user(username, email, password)
                user.save()
                user = authenticate(username=user, password=password)
                return redirect('/')
            else:
                print "User already exists"
                to_json = {"failed": "failed"}
                json = simplejson.dumps(to_json)
                return HttpResponse(json, mimetype='application/json')
        else:
            print "User already exists"
            to_json = {"failed": "failed"}
            json = simplejson.dumps(to_json)
            return HttpResponse(json, mimetype='application/json')


def add_review(request, toilet_id):
    toilet = get_object_or_404(Toilet, id=toilet_id)
    return render(
        request, 'lavoratr/add_review.html',
        {'form': ReviewForm, 'toilet': toilet}
    )


def submit_review(request):
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            toilet = Toilet.objects.get(id=request.POST['toilet_id'])
            current_time = timezone.now()
            rating = int(request.POST['rating'])
            comment_box = request.POST['comment_box']
            if rating == 1:
                toilet.positive_ratings += 1
            elif rating == 2:
                toilet.negative_ratings += 1
            toilet.save()
            new_review = Review.objects.create(
                toilet=toilet,
                rating=rating,
                comment_box=comment_box,
                created=current_time
            )
            new_review.save()

            return HttpResponse('Yes')

    toilet = get_object_or_404(Toilet, id=request.POST['toilet_id'])
    return render(
        request, 'lavoratr/add_review.html',
        {'form': ReviewForm, 'toilet': toilet}
    )


def add_toilet(request, lat, lng):
    float_lat = float(lat)
    float_lng = float(lng)
    point = Point(float_lng, float_lat)
    return render(
        request, 'lavoratr/add_toilet.html',
        {'form': ToiletForm, 'point': point.hex}
    )


def submit_toilet(request):
    if request.method == 'POST':
        form = ToiletForm(request.POST)
        if form.is_valid():
            if 'single_occupancy' in request.POST:
                single_occupancy_bool = True
            else:
                single_occupancy_bool = False

            if 'accesible' in request.POST:
                accesible_bool = True
            else:
                accesible_bool = False

            if 'station' in request.POST:
                station_bool = True
            else:
                station_bool = False

            rating = int(request.POST['rating'])
            if rating == 1:
                pos_rating = 1
                neg_rating = 0
            elif rating == 2:
                pos_rating = 0
                neg_rating = 1

            current_time = timezone.now()
            new_toilet = Toilet.objects.create(
                location=request.POST['location'],
                building=request.POST['building'],
                positive_ratings=pos_rating,
                negative_ratings=neg_rating,
                gender=request.POST['gender'],
                created=current_time,
                single_occupancy=single_occupancy_bool,
                accesible=accesible_bool,
                station=station_bool,
                times_authenticated=1,
                point=Point(
                    float(request.POST['lng']),
                    float(request.POST['lat'])
                )
            )

            new_toilet.save()

            new_id = new_toilet.id
            new_toilet = Toilet.objects.get(id=new_id)

            new_review = Review.objects.create(
                toilet=new_toilet,
                rating=rating,
                comment_box=request.POST['comment_box'],
                created=current_time,
            )
            new_review.save()

            return HttpResponseRedirect('/')
    point = Point(float(request.POST['lng']), float(request.POST['lat']))
    context = {'form': ToiletForm, 'point': point.hex}

    return render(request, 'lavoratr/add_toilet.html', context)

lavoratr/templates/lavoratr/add_review.html
<!DOCTYPE html>
{% load staticfiles %}
<h1>Add a Review</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'lavoratr:submit_review' %}" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input id="toilet_id" name="toilet_id" type="hidden" value="{{ toilet.id }}"/>
  <input type="submit" value="Submit">
</form>

lavoratr/templates/lavoratr/add_toilet.html
<!DOCTYPE html>
{% load staticfiles %}
<head>
    <link rel="stylesheet" href="{% static 'lavoratr/add_toilet.css' %}" />
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300' rel='stylesheet' type='text/css'>
</head>
<body>
	<div id="content">
		{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

		<form action="{% url 'lavoratr:submit_toilet' %}" method="post">
		{% csrf_token %}
		{{ form.as_p }}
		<input geom_type="POINT" id="id_point" name="point" type="hidden" value="{{ point }}"/>
		<div id="submit_button">Submit</div>
		</form>
	</div>
</body>

lavoratr/templates/lavoratr/base.html
{% load staticfiles %}
<html>
  <head>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" media="screen">
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <title>Lavoratr</title>
    {% block extra_head %}{% endblock %}
  </head>

  <body>
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>                        
          </button>
          <a class="navbar-brand" href="{% url 'lavoratr:index' %}">Lavoratr</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'lavoratr:index' %}">Home</a></li>
            <li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#add_toilet" id="add_toilet"><i class="glyphicon glyphicon-plus"> </i></a></li>
            <li><a href="#refresh" id="refresh"><i class="glyphicon glyphicon-refresh"> </i></a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="glyphicon glyphicon-user"> </i> <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="{% url 'lavoratr:login' %}">Sign In</a></li>
                <li><a href="{% url 'lavoratr:registration' %}">Register</a></li>
              </ul>
            </li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
  
    {% block content %}
    {% endblock %}

  </body>
</html>

lavoratr/templates/lavoratr/detail.html
<!DOCTYPE html>
{% load staticfiles %}
<html>

<head>
	<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="{% static 'lavoratr/detail.css' %}" />
	<title>Lavoratr Toilet #{{ toilet.id }}</title>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
</head>
<h1>{{  toilet.location  }}, {{  toilet.building  }}</h1>
<body>
	<div><p id="rating"></p></div>
	<div id="rate_bar">
		<div id="good_ratings"></div>
		<div id="bad_ratings"></div>
	</div>
	<div><p id="times_rated">Based on <span id='calc_times_rated'></span> reviews.</p></div>
	<div><p id="gender">Gender: {{ toilet.gender }}</p></div>
	<div><p id="single_occupancy">Single Occupancy: {{ toilet.single_occupancy }}</p></div>
	<div><p id="accesible">Accesible: {{ toilet.accesible }}</p></div>
	<div><p id="station">Station: {{ toilet.station }}</p></div>
	<p>Comments:</p>
	<div id="comment_box">
	{% for review_comments in reviews %} 
	    <p class="comments"> {{ review_comments.created }}:  {{ review_comments.rating }}
	    {% if review_comments.comment_box != ""  %}
	        <div class="comment"{{ review_comments.comment_box }}</div>
	    {% endif %}
	    </p>
	{% endfor %}
    </div>
	<script>
		var $rating = {{ toilet.positive_ratings }};
	    var $times_rated = 
	        {{ toilet.positive_ratings }} + {{ toilet.negative_ratings }};

        $( document ).ready(function() {
            var real_rating = $rating / $times_rated;
            $( "#times_rated").children("#calc_times_rated").text($times_rated);
            $( "#rating" ).html(real_rating);
            $( "#good_ratings" ).css("width", real_rating * 100);
            $( "#bad_ratings" ).css("width", 100 - real_rating * 100);
        });
    </script>

    <div id="link_div">
    	<a href="/add_review/{{ toilet.id }}/">Add Review</a>
    </div>
</body>
</html>

lavoratr/templates/lavoratr/toilet.html
{% extends "lavoratr/base.html" %}
{% load static %}
{% block extra_head %}
  <link rel="stylesheet" type="text/css" href="{% static 'lavoratr/toilet_map.css' %}" />
  <script src='https://api.tiles.mapbox.com/mapbox.js/v2.1.4/mapbox.js'></script>
  <link href='https://api.tiles.mapbox.com/mapbox.js/v2.1.4/mapbox.css' rel='stylesheet' />
  <link rel="stylesheet" type="text/css" href="{% static 'lavoratr/toilet_map.css' %}" />
{% endblock %}

{% block content %}
  <div id="map"></div>

  <div class="modal fade" id="basicModal" tabindex="-1" role="dialog" aria-labelledby="basicModal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&amp;times;</button>
            <h4 class="modal-title" id="myModalLabel">Modal title</h4>
            </div>
            <div class="modal-body">
                <h3>Modal Body</h3>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
        </div>
    </div>
  </div>
</div>
  <script type="text/javascript" src="{% static 'lavoratr/toilet_map.js' %}"></script>
{% endblock %}

lavoratr/templates/lavoratr/user_login.html
{% extends "lavoratr/base.html" %}
{% load static %}
{% block extra_head %}
    <link rel="stylesheet" type="text/css" href="{% static 'lavoratr/user_login.css' %}" />
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <form role="form" action="/login_submit" method="post">
            {% csrf_token %}
            <div class="col-lg-6">
                <div class="well well-sm"><strong><span class="glyphicon glyphicon-asterisk"></span>Required Field</strong></div>
                <div class="form-group">
                    <label for="InputUsername">Enter Username</label>
                    <div class="input-group">
                        <input type="text" class="form-control" name="InputUsername" id="InputUsername" placeholder="Enter Username" required>
                        <span class="input-group-addon"><span class="glyphicon glyphicon-asterisk"></span></span>
                    </div>
                    </div>
                <div class="form-group">
                    <label for="InputPassword">Enter Password</label>
                    <div class="input-group">
                        <input type="password" class="form-control" name="InputPassword" id="InputPassword" placeholder="Enter Password" required>
                        <span class="input-group-addon"><span class="glyphicon glyphicon-asterisk"></span></span>
                    </div>
                </div>
        </form>
        <div class="col-lg-5 col-md-push-1">
            <div class="col-md-12">
                <div class="alert alert-success">
                    <strong><span class="glyphicon glyphicon-ok"></span> Success! Message sent.</strong>
                </div>
                <div class="alert alert-danger">
                    <span class="glyphicon glyphicon-remove"></span><strong> Error! Please check all page inputs.</strong>
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript" src="{% static 'lavoratr/user_login.js' %}"></script>
</div>
{% endblock %}

lavoratr/templates/lavoratr/user_registration.html
{% extends "lavoratr/base.html" %}
{% load static %}
{% block extra_head %}
    <link rel="stylesheet" type="text/css" href="{% static 'lavoratr/user_registration.css' %}" />
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <form role="form" action="/registration_submit" method="post">
            {% csrf_token %}
            <div class="col-lg-6">
                <div class="well well-sm"><strong><span class="glyphicon glyphicon-asterisk"></span>Required Field</strong></div>
                <div class="form-group">
                    <label for="InputEmail">Enter Email</label>
                    <div class="input-group">
                        <input type="email" class="form-control" id="InputEmail" name="InputEmail" placeholder="Enter Email" required>
                        <span class="input-group-addon"><span class="glyphicon glyphicon-asterisk"></span></span>
                    </div>
                </div>
                <div class="form-group">
                    <label for="InputUsername">Enter Username</label>
                    <div class="input-group">
                        <input type="text" class="form-control" name="InputUsername" id="InputUsername" placeholder="Enter Username" required>
                        <span class="input-group-addon"><span class="glyphicon glyphicon-asterisk"></span></span>
                    </div>
                </div>
                <div class="form-group">
                    <label for="InputPassword">Enter Password</label>
                    <div class="input-group">
                        <input type="password" class="form-control" name="InputPassword" id="InputPassword" placeholder="Enter Password" required>
                        <span class="input-group-addon"><span class="glyphicon glyphicon-asterisk"></span></span>
                    </div>
                </div>
                <div class="form-group">
                    <label for="InputPasswordConfirm">Confirm Password</label>
                    <div class="input-group">
                        <input type="password" class="form-control" name="InputPasswordConfirm" id="InputPasswordConfirm" placeholder="Confirm Pasword" required>
                        <span class="input-group-addon"><span class="glyphicon glyphicon-asterisk"></span></span>
                    </div>
                </div>
                <input type="submit" name="submit" id="submit" value="Submit" class="btn btn-info pull-right">
            </div>
        </form>
        <div class="col-lg-5 col-md-push-1">
            <div class="col-md-12">
                <div class="alert alert-success">
                    <strong><span class="glyphicon glyphicon-ok"></span> Success! Message sent.</strong>
                </div>
                <div class="alert alert-danger">
                    <span class="glyphicon glyphicon-remove"></span><strong> Error! Please check all page inputs.</strong>
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript" src="{% static 'lavoratr/user_registration.js' %}"></script>
</div>
{% endblock %}